Dataset at https://www.kaggle.com/neechalkaran 

Eventhough Tamil has definite grammar to develop rulebased approach, It is an experimental work using ML Approach to predict.



In [24]:
#to predict Grammar type. Supervised Learning/Classification
#!pip install transformers  
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_cs
import os # The OS module in python provides functions for interacting with the operating system


from tqdm import tqdm, trange# for progress bar
data = pd.read_csv("/content/kaggle/Error Annotated Corpus.csv", encoding="utf=8").fillna(method="ffill")
#data.tail(10)# show last 10 rows


train_documents = [word for word in data['Corrected words & its']]
train_labels = [tag for tag in data['Annotation']]


from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
count_vectorizer = CountVectorizer(binary="true")
train_documents = count_vectorizer.fit_transform(train_documents)


classifier = BernoulliNB().fit(train_documents, train_labels)#Naive Bayes 

def predictionType(sentence):
    prediction = classifier.predict(count_vectorizer.transform([sentence]))
    print(prediction[0])


predictionType("அதிகச் செயல்திறனுடையதாக")        
predictionType("இனையமைச்சர் பார்த்தார்")       
predictionType(" ஆதரவை செய்து ")       

மகர ஈற்று
தட்டுப்பிழை
தட்டுப்பிழை


In [29]:
#to predict sandhi presence between two words
#!pip install transformers  
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_cs
import os # The OS module in python provides functions for interacting with the operating system


from tqdm import tqdm, trange# for progress bar
data = pd.read_csv("/content/kaggle/Error Annotated Corpus.csv", encoding="utf=8").fillna(method="ffill")


train_documents = [word for word in data['Corrected words & its']]
train_labels = ['true' for tag in data['Annotation']]
train_documents2 = [word for word in data['Error word & consecutive word']]
train_labels2 = ['false' for tag in data['Annotation']]

for i in train_documents2:
    train_documents.append(i) 
for i in train_labels2:
    train_labels.append(i) 

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
count_vectorizer = CountVectorizer(binary="true")
train_documents = count_vectorizer.fit_transform(train_documents)
classifier = BernoulliNB().fit(train_documents, train_labels)

def predictionType(sentence):
    prediction = classifier.predict(count_vectorizer.transform([sentence]))
    print(prediction[0])


predictionType("முதல்  கட்டத்தில்")   
predictionType("இறுதி கட்டத்தில்")     
predictionType("அதோடு கட்டத்தில்")     
predictionType("அதனை கண்டார்")     

false
true
false
true


In [9]:
#To predict District from given sentence which contains Constituency 
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import train_test_split

#from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree



data = pd.read_csv("/content/kaggle/Tamil Nadu Habitants.csv", encoding="utf=8").fillna(method="ffill")
data.tail(10)# show last 10 rows


#data.info()
#data.isnull()
#data.describe()

#train_documents = [word for word in data['குடியிருப்பு']]
train_documents = [word for word in data['தொகுதி']]
train_labels = [tag for tag in data['மாவட்டம்']]

X_train, X_test, y_train, y_test = train_test_split(train_documents, train_labels, test_size=0.1, random_state=1337)

vectorizer = CountVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(y_pred)


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (24) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


                            precision    recall  f1-score   support

         அரியலூர் மாவட்டம்       1.00      1.00      1.00        69
    இராணிப்பேட்டை மாவட்டம்       0.66      1.00      0.79       120
     இராமநாதபுரம் மாவட்டம்       0.81      0.74      0.77       131
            ஈரோடு மாவட்டம்       0.85      0.79      0.82       207
           கடலூர் மாவட்டம்       1.00      0.59      0.74       229
     கன்னியாகுமரி மாவட்டம்       1.00      0.64      0.78       159
            கரூர் மாவட்டம்       1.00      0.75      0.85       106
   கள்ளக்குறிச்சி மாவட்டம்       1.00      1.00      1.00       150
      காஞ்சிபுரம் மாவட்டம்       0.42      0.74      0.54       140
      கிருஷ்ணகிரி மாவட்டம்       1.00      1.00      1.00       187
    கோயம்புத்தூர் மாவட்டம்       0.19      1.00      0.31       308
         சிவகங்கை மாவட்டம்       1.00      0.74      0.85        96
     செங்கல்பட்டு மாவட்டம்       1.00      0.80      0.89       262
           சென்னை மாவட்டம்       0.88      0.70

In [16]:
#Examples
teststring = vectorizer.transform(["   சோழிங்கநல்லூர் அருகே வேளச்சேரி பேருந்து நிலையத்தில் புதிய நடைமேடை திறந்து வைக்கப்பட்டது  "])
custom_pred = dt.predict(teststring)
print(custom_pred)
teststring = vectorizer.transform([" மதுரை அருகே திருப்பரங்குன்றம் கோயில் தேர் திருவிழா நடைபெற்றது "])
custom_pred = dt.predict(teststring)
print(custom_pred)

['செங்கல்பட்டு மாவட்டம்']
['மதுரை மாவட்டம்']


In [29]:

classifier=RandomForestClassifier()

classifier=classifier.fit(X_train,y_train)
predicted=classifier.predict(X_test)
  
#printing the results
print ('Confusion Matrix :')
print(confusion_matrix(y_test, predicted))
print ('Accuracy Score :',accuracy_score(y_test, predicted))
print ('Report : ')
print (classification_report(y_test, predicted))

Confusion Matrix :
[[ 69   0   0 ...   0   0   0]
 [  0 120   0 ...   0   0   0]
 [  0   0  97 ...   0   0   0]
 ...
 [  0   0   0 ...  82   0   0]
 [  0   0   0 ...   0  50   0]
 [  0   0   0 ...   0   0  64]]
Accuracy Score : 0.7257303039244615
Report : 
                            precision    recall  f1-score   support

         அரியலூர் மாவட்டம்       1.00      1.00      1.00        69
    இராணிப்பேட்டை மாவட்டம்       0.66      1.00      0.79       120
     இராமநாதபுரம் மாவட்டம்       0.81      0.74      0.77       131
            ஈரோடு மாவட்டம்       0.85      0.79      0.82       207
           கடலூர் மாவட்டம்       1.00      0.59      0.74       229
     கன்னியாகுமரி மாவட்டம்       1.00      0.64      0.78       159
            கரூர் மாவட்டம்       1.00      0.75      0.85       106
   கள்ளக்குறிச்சி மாவட்டம்       1.00      1.00      1.00       150
      காஞ்சிபுரம் மாவட்டம்       0.42      0.74      0.54       140
      கிருஷ்ணகிரி மாவட்டம்       1.00      1.00      1.00     

In [18]:
# to predict location. Supervised Learning/Classification
#!pip install transformers  
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_cs
import os # The OS module in python provides functions for interacting with the operating system


from tqdm import tqdm, trange# for progress bar
data = pd.read_csv("/content/kaggle/Tamil Nadu Habitants.csv", encoding="utf=8").fillna(method="ffill")
data.tail(10)# show last 10 rows


#data.info()
#data.isnull()
#data.describe()
#data['Annotation'].value_counts()#to get count
#data['Annotation'].unique()

train_documents = [word for word in data['தொகுதி']]
train_labels = [tag for tag in data['மாவட்டம்']]
#print(train_documents[10])

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
count_vectorizer = CountVectorizer(binary="true")
train_documents = count_vectorizer.fit_transform(train_documents)

classifier = BernoulliNB().fit(train_documents, train_labels)#Naive Bayes 

def predictionType(sentence):
    prediction = classifier.predict(count_vectorizer.transform([sentence]))
    print(prediction[0])
predictionType(" கடையநல்லூரில் புதிய காவல் நிலையம் கட்டப்படுகிறது ")        


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (24) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


தென்காசி மாவட்டம்
